CREATE DATABASE QLKVC

USE QLKVC
 DROP TABLE KHU_VUI_CHOI
CREATE TABLE KHU_VUI_CHOI (
	MaKVC			VARCHAR(10) PRIMARY KEY,
	TenKVC			VARCHAR(50),
	DiaChi			VARCHAR(100),
	GioMoCua		TIME,
	GioDongCua		TIME,
	TrangThai		VARCHAR(10)
)

CREATE TABLE KHU_VUC (
	MaKhuVuc		VARCHAR(10) PRIMARY KEY,
	TenKhuVuc		VARCHAR(50),
	MoTa			VARCHAR(100),
	SucChuaToiDa	INT,
	MaKVC			VARCHAR(10)
)

CREATE TABLE VE (
	MaVe			VARCHAR(10),
	MaKhuVuc		VARCHAR(10),
	TenVe			VARCHAR(50),
	LoaiVe			VARCHAR(20),
	GiaCoBan		INT,
	HieuLucTu		TIME,
	HieuLucDen		TIME,
	PRIMARY KEY(MaVe, MaKhuVuc)
)

CREATE TABLE KHACH_HANG (
	MaKH			VARCHAR(10) PRIMARY KEY,
	HoTen			VARCHAR(50),
	SDT				VARCHAR(20),
	Email			VARCHAR(50),
	NgaySinh		SMALLDATETIME,
	NgayTao			SMALLDATETIME,
	LoaiKH			VARCHAR(10)
)

CREATE TABLE DON_MUA (
	MaDon			VARCHAR(10) PRIMARY KEY,
	MaKH			VARCHAR(10),
	NgayMua			SMALLDATETIME,
	TongTien		INT,
	PhuongThucTT	VARCHAR(20),
	TrangThai		VARCHAR(10)
)

CREATE TABLE CT_DON_MUA (
	MaDon			VARCHAR(10),
	MaVe			VARCHAR(10),
	SoLuong			INT,
	DonGia			INT,
	NgaySuDung		SMALLDATETIME,
	MaQR			VARCHAR(10),
	PRIMARY KEY(MaDon, MaVe)
)
ALTER TABLE KHU_VUC
ADD CONSTRAINT FK_MAKHUVUC_KVC FOREIGN KEY(MAKVC) REFERENCES KHU_VUI_CHOI(MAKVC)
ALTER TABLE VE 
ADD CONSTRAINT FK_MAKHUVUC_VE FOREIGN KEY(MAKHUVUC) REFERENCES KHU_VUC(MAKHUVUC)
ALTER TABLE DON_MUA 
ADD CONSTRAINT FK_MAKH_DM FOREIGN KEY(MAKH) REFERENCES KHACH_HANG(MAKH)
ALTER TABLE CT_DON_MUA 
ADD CONSTRAINT FK_MADON_CT FOREIGN KEY(MADON) REFERENCES DON_MUA(MADON)
ALTER TABLE CT_DON_MUA 
ADD CONSTRAINT FK_MAVE_CT FOREIGN KEY(MAVE) REFERENCES VE(MAVE)

--1.
SELECT MADON,NGAYMUA,TONGTIEN
FROM DON_MUA  
WHERE MAKH ='KH01'
GROUP BY MADON,NGAYMUA,TONGTIEN
ORDER BY NGAYMUA DESC
--2.
SELECT KV.MAKHUVUC,TENKHUVUC,SUM(SOLUONG) AS TONGSOVE
FROM CT_DON_MUA  CT
JOIN VE 
ON VE.MAVE =  CT.MAVE
JOIN KHU_VUC  KV
ON VE.MAKHUVUC = KV.MAKHUVUC
GROUP BY KV.MAKHUVUC,TENKHUVUC 
--3.
SELECT KH.MAKH,HOTEN,COUNT(VE.MAVE) AS SOVE 
FROM KHACH_HANG KH 
JOIN DON_MUA DM 
ON DM.MAKH = KH.MAKH 
JOIN CT_DON_MUA CT 
ON CT.MADON = DM.MADON 
JOIN VE 
ON VE.MAVE = CT.MAVE 
GROUP BY KH.MAKH,HOTEN
HAVING COUNT(VE.MAVE) = (SELECT COUNT(V1.MAKHUVUC)
							FROM CT_DON_MUA CT1
							JOIN VE V1 ON V1.MAVE = CT1.MAVE